# -*- coding: utf-8 -*-
"""framework.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1abA414pvOoD8vhiZYiNfEVuZm59_UUpe
"""
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

#Read dataset
df = pd.read_csv('mc-donalds-menu.csv')
#To predict calories the columns needed are: Calories, Total fat, Carbohydrates, Sugars and Protein
columns=["Calories", "Total Fat", "Carbohydrates","Sugars","Protein"]
#Create new dataset with relevant variables
df=df[columns].copy()

#Split into x,y
x=df.drop(["Calories"],axis=1).copy()
y=df.Calories

#splitting data into train and test sets (80-20)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.25, random_state=1) # 0.25 x 0.8 = 0.2

#Variable for decision tree regressor
model=DecisionTreeRegressor()

#Training the model with the train sets
model.fit(x_train, y_train)

#Prediction on train
y_hat_train=model.predict(x_train)

#Calculate metrics
mse_train=mean_squared_error(y_hat_train,y_train)
mae_train=mean_absolute_error(y_hat_train,y_train)
r2_train=r2_score(y_hat_train,y_train)

print("MSE=", mse_train)
print("MAE=", mae_train)
print("R2=" ,r2_train)

#Prediction on test
y_hat_test=model.predict(x_test)

#Calculate metrics
mse_test=mean_squared_error(y_hat_test,y_test)
mae_test=mean_absolute_error(y_hat_test,y_test)
r2_test=r2_score(y_hat_test,y_test)

print("MSE=", mse_test)
print("MAE=", mae_test)
print("R2=" ,r2_test)

#Prediction on validation
y_hat_val=model.predict(x_val)

#Calculate metrics
mse_val=mean_squared_error(y_hat_val,y_val)
mae_val=mean_absolute_error(y_hat_val,y_val)
r2_val=r2_score(y_hat_val,y_val)

print("MSE=", mse_val)
print("MAE=", mae_val)
print("R2=" ,r2_val)